# Generated by Django 3.2.4 on 2021-06-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_photo'),
        ('rooms', '0006_alter_photo_file'),
    ]

    operations = [
    ]
