# Generated by Django 3.2.3 on 2021-06-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_room', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
