# Generated by Django 3.2.4 on 2021-06-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
        ('users', '0002_alter_user_birthdate'),
    ]

    operations = [
    ]
